site_name: datarepo
site_url: https://data-repo.io
repo_url: https://github.com/neuralinkcorp/datarepo/
repo_name: neuralink/datarepo

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: white
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - toc.integrate
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.tooltips
  logo: images/banner.png
  favicon: images/logo.png
  custom_dir: docs/stylesheets
  icon:
    repo: fontawesome/brands/github

extra_javascript:
  - javascripts/shortcuts.js
  - examples/web_catalog/assets/*.js

plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets

extra_css:
  - stylesheets/extra.css
  - examples/web_catalog/assets/*.css

docs_dir: docs
site_dir: site

nav:
  - Home: /
  - User Guide: user-guide.md
  - API docs: api-docs.md

hooks:
  - docs/hooks.py
